# Generated by Django 4.2.5 on 2023-09-17 02:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoalTemplateNutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendedValue', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('barcode', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('isCategory', models.BooleanField(default=False)),
                ('parentNutrient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nutrition.nutrient')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionalGoalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nutrients', models.ManyToManyField(through='nutrition.GoalTemplateNutrient', to='nutrition.nutrient')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserNutritionalGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.nutritionalgoaltemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServingSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.unit')),
            ],
        ),
        migrations.AddField(
            model_name='nutrient',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.unit'),
        ),
        migrations.CreateModel(
            name='ItemNutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.item')),
                ('nutrientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.nutrient')),
            ],
        ),
        migrations.CreateModel(
            name='ItemBioactive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.item')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.unit')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='nutrients',
            field=models.ManyToManyField(related_name='items', through='nutrition.ItemNutrient', to='nutrition.nutrient'),
        ),
        migrations.AddField(
            model_name='item',
            name='servingSize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.servingsize'),
        ),
        migrations.AddField(
            model_name='goaltemplatenutrient',
            name='nutrient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.nutrient'),
        ),
        migrations.AddField(
            model_name='goaltemplatenutrient',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.nutritionalgoaltemplate'),
        ),
        migrations.CreateModel(
            name='Consumed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumedAt', models.DateTimeField(auto_now_add=True)),
                ('portion', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('combinedItemId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nutrition.combineditem')),
                ('itemId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nutrition.item')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CombinedItemElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combinedItemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.combineditem')),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.item')),
                ('servingSize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.servingsize')),
            ],
        ),
    ]
