# Generated by Django 4.2.5 on 2023-11-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nutrition", "0002_alter_nutrient_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="abbreviation",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="name",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
