# Generated by Django 4.2.5 on 2023-11-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_alter_combineditemelement_portion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='calories',
            field=models.PositiveIntegerField(),
        ),
    ]
